[pytest]
testpaths = tests
pythonpath = .
addopts = -v --tb=short
markers =
    firefox: Firefox 브라우저 테스트
    chrome: Chrome 브라우저 테스트
    edge: Edge 브라우저 테스트
    smoke: quick smoke tests

# 터미널 로그
log_cli = true
log_cli_level = INFO

# 로그파일 저장
log_file = logs/test.log
log_file_mode = w
log_file_level = INFO

log_format = [%(asctime)s] [%(levelname)s] [%(name)s] %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
# pytest.ini에서 프로젝트 루트로 지정하여 tests 폴더에서 src 모듈을 import할 수 있도록 설정